#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] ; then
    if ! [ -e /etc/ld.so.conf.d/atlas.conf ] ; then touch /etc/ld.so.conf.d/atlas.conf ; fi
    if [ $(awk 'END {print NR}' /etc/ld.so.conf.d/atlas.conf) != $(cat /etc/ld.so.conf.d/atlas.conf | wc -l) ] ; then
	echo >> /etc/ld.so.conf.d/atlas.conf
    fi
    if ! grep -q '^/usr/lib/atlas$' /etc/ld.so.conf.d/atlas.conf ; then
	echo /usr/lib/atlas >> /etc/ld.so.conf.d/atlas.conf
    fi
fi

#DEBHELPER#
